### ISSUE TITLE
createHmac broken on 0.8

### ISSUE THREAD

**Issue by dominictarr** [dominictarr/crypto-browserify#33]
damn. Broke createHmac on node@0.8
testling is not running...
I'll look into this at first opportunity, shouldn't have pushed this.
probably you should not use 2.0 yet if you need createHmac
(strange, because createHash is fine, which is used by createHmac)

**Comment by dcousens** [comment]
This can be closed?

**Comment by calvinmetcalf** [comment]
I believe so
