### ISSUE TITLE
listCiphers vs getCiphers

### ISSUE THREAD

**Issue by guymguym** [dominictarr/crypto-browserify#91]
Hey, awesome project!

Is there a reason the name is listCiphers() in this module and not the same as in node.js crypto.getCiphers() ?

Maybe keep both for backwards compatibility, but it's surprising that getHashes is there and getCiphers is not...

**Comment by calvinmetcalf** [comment]
that is a bug, see calvinmetcalf/browserify-aes#15

**Comment by guymguym** [comment]
great!
